### ISSUE TITLE
LetsEncrypt Certificate of maven.dragons.plus is Expired

### ISSUE THREAD

**Issue by nausicaea** [Krysztal112233/krysztal-language-scala#1]
Hi there I just kindly wanted to let you know that the TLS certificate you issue on maven.dragons.plus expired on Oct 6 2024. This makes it impossible to download assets from your Maven repository. Please let me know if I can be of assistance :)

P.S. thank you so much for the scala adaptor!

**Comment by Krysztal112233** [comment]
Humm sorry for lately reply. I uploaded build result to my friend's maven, but his is busy recently.

I'll reupload build to new mvn these days, before I finished moving you can use `ModrinthMaven` instead

When I finished moving, I'll notified you. Thanks to your support :)

**Comment by nausicaea** [comment]
Hi Krysztal, no worries and no hurry! Thank you so much for your work. I will use Modrinth's maven for now, thanks!

**Comment by nausicaea** [comment]
A quick update: the LetsEncrypt certificate on maven.dragons.plus is now valid again, meaning that I can download the maven artefacts. As far as I'm concerned, there's no need for you to migrate to another maven.

**Comment by Krysztal112233** [comment]
Thanks for your notice and support :)
